import type { WorldMonitorSourceConfig } from '@/features/worldmonitor/types/worldmonitor_adapter';
import {
  FEED_OPERATION_TO_SOURCE_ID,
  FEED_SOURCE_CATALOG,
} from '@/features/worldmonitor/domain/worldmonitor_feed_catalog';

/**
 * Canonical per-source lifecycle mapping catalog.
 *
 * This table is the single source of truth that maps World Monitor sources
 * (both worldmonitor_hosted and direct_public) to lifecycle layers, default
 * evidence strength, event types and review defaults. It was migrated from
 * the legacy WorldMonitorIntakeConnector so that the live sync path and the
 * legacy signal connector share one configuration. See docs/27 for the
 * integration map this table implements.
 */
export const WORLDMONITOR_SOURCE_CATALOG: Record<string, WorldMonitorSourceConfig> = {
  // Category 6: Direct public sources (v0.7.9+)
  gdelt_doc_articles: {
    source_id: 'gdelt_doc_articles',
    source_name: 'GDELT DOC 2.0 Global News Articles',
    domain: 'osint',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'GLOBAL_NEWS_EVENT',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  coinbase_spot: {
    source_id: 'coinbase_spot',
    source_name: 'Coinbase Public Spot Price Quotes',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'CRYPTO_SPOT_PRICE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  eastmoney_concept_boards: {
    source_id: 'eastmoney_concept_boards',
    source_name: 'A-Share Concept Board Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'CONCEPT_BOARD_MOVE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  eastmoney_stock_quote: {
    source_id: 'eastmoney_stock_quote',
    source_name: 'A-Share Stock Quote Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'A_SHARE_QUOTE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  clinical_trials_gov: {
    source_id: 'clinical_trials_gov',
    source_name: 'US NIH ClinicalTrials.gov Studies',
    domain: 'health',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['data_confidence'],
    default_evidence_strength: 'E3',
    default_event_type: 'CLINICAL_TRIAL_UPDATE',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  un_comtrade_preview: {
    source_id: 'un_comtrade_preview',
    source_name: 'UN Comtrade Public Preview API',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'TRADE_FLOW_RECORDED',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },

  // Category 7: Leading vendor official disclosures & industry signals (v0.8.0+)
  sec_edgar_nvidia: {
    source_id: 'sec_edgar_nvidia',
    source_name: 'NVIDIA Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_apple: {
    source_id: 'sec_edgar_apple',
    source_name: 'Apple Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_tsmc: {
    source_id: 'sec_edgar_tsmc',
    source_name: 'TSMC Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  hacker_news_stories: {
    source_id: 'hacker_news_stories',
    source_name: 'Hacker News Developer Community Signal',
    domain: 'research',
    source_type: 'other',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
  fear_greed_index: {
    source_id: 'fear_greed_index',
    source_name: 'Crypto Fear & Greed Market Sentiment Index',
    domain: 'financial',
    source_type: 'other',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_SENTIMENT_INDEX',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  coingecko_trending: {
    source_id: 'coingecko_trending',
    source_name: 'CoinGecko Trending Market Search Signal',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'name',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E1',
    default_event_type: 'MARKET_TRENDING_ASSET',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
  cailian_telegraph: {
    source_id: 'cailian_telegraph',
    source_name: 'Cailian Press 24/7 Rolling Telegraph',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['reality', 'pricing'],
    default_evidence_strength: 'E1',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  wsj_business: {
    source_id: 'wsj_business',
    source_name: 'The Wall Street Journal - Global Business & Markets',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction', 'pricing'],
    default_evidence_strength: 'E1',
    default_event_type: 'PREMIUM_FINANCIAL_REPORTING',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  reuters_biz: {
    source_id: 'reuters_biz',
    source_name: 'Reuters Business & Finance Wire',
    domain: 'geopolitics',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'GLOBAL_WIRE_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  tech_crunch: {
    source_id: 'tech_crunch',
    source_name: 'TechCrunch Startups and VC News',
    domain: 'technology',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'TECH_STARTUP_FUNDING',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  nts_finance: {
    source_id: 'nts_finance',
    source_name: 'NewTimeSpace Finance RSS',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  nts_technology: {
    source_id: 'nts_technology',
    source_name: 'NewTimeSpace Technology RSS',
    domain: 'technology',
    source_type: 'news',
    primary_layer: 'reality',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'TECH_STARTUP_FUNDING',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  nts_etf: {
    source_id: 'nts_etf',
    source_name: 'NewTimeSpace ETF Fund Flows',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E3',
    default_event_type: 'INSTITUTIONAL_MACRO_DATA',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  nts_research: {
    source_id: 'nts_research',
    source_name: 'NewTimeSpace Research Reports',
    domain: 'research',
    source_type: 'official',
    primary_layer: 'pricing',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'INSTITUTIONAL_BROKER_REPORT',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_macro: {
    source_id: 'investing_macro',
    source_name: 'Investing.com Macro & Market News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'GLOBAL_WIRE_NEWS',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_stock: {
    source_id: 'investing_stock',
    source_name: 'Investing.com Stock Market News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  investing_analysis: {
    source_id: 'investing_analysis',
    source_name: 'Investing.com Market Analysis',
    domain: 'research',
    source_type: 'other',
    primary_layer: 'pricing',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'PREMIUM_FINANCIAL_REPORTING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_crypto: {
    source_id: 'investing_crypto',
    source_name: 'Investing.com Crypto News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_TRENDING_ASSET',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
};

/**
 * Maps live operation ids to canonical catalog keys so the sync path resolves
 * the same per-source lifecycle configuration as the legacy connector.
 */
const OPERATION_TO_SOURCE_ID: Record<string, string> = {
  DirectGdeltDocArticles: 'gdelt_doc_articles',
  DirectCoinbaseSpotPrice: 'coinbase_spot',
  DirectEastmoneyConceptBoards: 'eastmoney_concept_boards',
  DirectEastmoneyStockQuote: 'eastmoney_stock_quote',
  DirectClinicalTrialsGovStudies: 'clinical_trials_gov',
  DirectUnComtradePreview: 'un_comtrade_preview',
  DirectSecEdgarNvidia: 'sec_edgar_nvidia',
  DirectSecEdgarApple: 'sec_edgar_apple',
  DirectSecEdgarTsmc: 'sec_edgar_tsmc',
  DirectHackerNewsStories: 'hacker_news_stories',
  DirectFearGreedIndex: 'fear_greed_index',
  DirectCoinGeckoTrending: 'coingecko_trending',
  DirectCailianTelegraph: 'cailian_telegraph',
  DirectWSJBusiness: 'wsj_business',
  DirectWSJChinese: 'wsj_business',
  DirectReutersBiz: 'reuters_biz',
  DirectTechCrunch: 'tech_crunch',
  DirectNtsFinance: 'nts_finance',
  DirectNtsTechnology: 'nts_technology',
  DirectNtsEtf: 'nts_etf',
  DirectNtsResearch: 'nts_research',
  DirectInvestingMacro: 'investing_macro',
  DirectInvestingStock: 'investing_stock',
  DirectInvestingAnalysis: 'investing_analysis',
  DirectInvestingCrypto: 'investing_crypto',
};

export function sourceConfigForSourceId(sourceId: string): WorldMonitorSourceConfig | null {
  return WORLDMONITOR_SOURCE_CATALOG[sourceId] ?? FEED_SOURCE_CATALOG[sourceId] ?? null;
}

export function operationSourceConfig(operationId: string): WorldMonitorSourceConfig | null {
  const sourceId = OPERATION_TO_SOURCE_ID[operationId] ?? FEED_OPERATION_TO_SOURCE_ID[operationId];
  return sourceId ? sourceConfigForSourceId(sourceId) : null;
}
