import type { WorldMonitorSourceConfig } from '@/features/worldmonitor/types/worldmonitor_adapter';
import {
  FEED_OPERATION_TO_SOURCE_ID,
  FEED_SOURCE_CATALOG,
} from '@/features/worldmonitor/domain/worldmonitor_feed_catalog';

/**
 * Canonical per-source lifecycle mapping catalog.
 *
 * This table is the single source of truth that maps World Monitor sources
 * (both worldmonitor_hosted and direct_public) to lifecycle layers, default
 * evidence strength, event types and review defaults. It was migrated from
 * the legacy WorldMonitorIntakeConnector so that the live sync path and the
 * legacy signal connector share one configuration. See docs/27 for the
 * integration map this table implements.
 */
export const WORLDMONITOR_SOURCE_CATALOG: Record<string, WorldMonitorSourceConfig> = {
  // Category 6: Direct public sources (v0.7.9+)
  gdelt_doc_articles: {
    source_id: 'gdelt_doc_articles',
    source_name: 'GDELT DOC 2.0 Global News Articles',
    domain: 'osint',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'GLOBAL_NEWS_EVENT',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  coinbase_spot: {
    source_id: 'coinbase_spot',
    source_name: 'Coinbase Public Spot Price Quotes',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'CRYPTO_SPOT_PRICE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  eastmoney_concept_boards: {
    source_id: 'eastmoney_concept_boards',
    source_name: 'A-Share Concept Board Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'CONCEPT_BOARD_MOVE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  eastmoney_stock_quote: {
    source_id: 'eastmoney_stock_quote',
    source_name: 'A-Share Stock Quote Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'A_SHARE_QUOTE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  clinical_trials_gov: {
    source_id: 'clinical_trials_gov',
    source_name: 'US NIH ClinicalTrials.gov Studies',
    domain: 'health',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['data_confidence'],
    default_evidence_strength: 'E3',
    default_event_type: 'CLINICAL_TRIAL_UPDATE',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  un_comtrade_preview: {
    source_id: 'un_comtrade_preview',
    source_name: 'UN Comtrade Public Preview API',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'TRADE_FLOW_RECORDED',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },

  // Category 7: Leading vendor official disclosures & industry signals (v0.8.0+)
  sec_edgar_nvidia: {
    source_id: 'sec_edgar_nvidia',
    source_name: 'NVIDIA Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_apple: {
    source_id: 'sec_edgar_apple',
    source_name: 'Apple Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_tsmc: {
    source_id: 'sec_edgar_tsmc',
    source_name: 'TSMC Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  hacker_news_stories: {
    source_id: 'hacker_news_stories',
    source_name: 'Hacker News Developer Community Signal',
    domain: 'research',
    source_type: 'other',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
  fear_greed_index: {
    source_id: 'fear_greed_index',
    source_name: 'Crypto Fear & Greed Market Sentiment Index',
    domain: 'financial',
    source_type: 'other',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_SENTIMENT_INDEX',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  coingecko_trending: {
    source_id: 'coingecko_trending',
    source_name: 'CoinGecko Trending Market Search Signal',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'name',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E1',
    default_event_type: 'MARKET_TRENDING_ASSET',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
  cailian_telegraph: {
    source_id: 'cailian_telegraph',
    source_name: 'Cailian Press 24/7 Rolling Telegraph',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['reality', 'pricing'],
    default_evidence_strength: 'E1',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  wsj_business: {
    source_id: 'wsj_business',
    source_name: 'The Wall Street Journal - Global Business & Markets',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction', 'pricing'],
    default_evidence_strength: 'E1',
    default_event_type: 'PREMIUM_FINANCIAL_REPORTING',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  reuters_biz: {
    source_id: 'reuters_biz',
    source_name: 'Reuters Business & Finance Wire',
    domain: 'geopolitics',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'GLOBAL_WIRE_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  tech_crunch: {
    source_id: 'tech_crunch',
    source_name: 'TechCrunch Startups and VC News',
    domain: 'technology',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'TECH_STARTUP_FUNDING',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  nts_finance: {
    source_id: 'nts_finance',
    source_name: 'NewTimeSpace Finance RSS',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  nts_technology: {
    source_id: 'nts_technology',
    source_name: 'NewTimeSpace Technology RSS',
    domain: 'technology',
    source_type: 'news',
    primary_layer: 'reality',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'TECH_STARTUP_FUNDING',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  nts_etf: {
    source_id: 'nts_etf',
    source_name: 'NewTimeSpace ETF Fund Flows',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E3',
    default_event_type: 'INSTITUTIONAL_MACRO_DATA',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  nts_research: {
    source_id: 'nts_research',
    source_name: 'NewTimeSpace Research Reports',
    domain: 'research',
    source_type: 'official',
    primary_layer: 'pricing',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'INSTITUTIONAL_BROKER_REPORT',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_macro: {
    source_id: 'investing_macro',
    source_name: 'Investing.com Macro & Market News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'GLOBAL_WIRE_NEWS',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_stock: {
    source_id: 'investing_stock',
    source_name: 'Investing.com Stock Market News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_FLASH_NEWS',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  investing_analysis: {
    source_id: 'investing_analysis',
    source_name: 'Investing.com Market Analysis',
    domain: 'research',
    source_type: 'other',
    primary_layer: 'pricing',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'PREMIUM_FINANCIAL_REPORTING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  investing_crypto: {
    source_id: 'investing_crypto',
    source_name: 'Investing.com Crypto News',
    domain: 'financial',
    source_type: 'news',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_TRENDING_ASSET',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  // --- First Batch (High Value Signals) ---
  huggingface: { source_id: 'huggingface', source_name: 'HuggingFace Hub Models', domain: 'technology', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E2', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  github_issues: { source_id: 'github_issues', source_name: 'GitHub Issues', domain: 'technology', source_type: 'other', primary_layer: 'name', secondary_layers: ['friction'], default_evidence_strength: 'E2', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'maintain', default_polarity: 'negative', default_confidence: 'medium' },
  github_trending: { source_id: 'github_trending', source_name: 'GitHub Trending Repos', domain: 'technology', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E2', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  arxiv_ai: { source_id: 'arxiv_ai', source_name: 'arXiv AI Preprints', domain: 'research', source_type: 'news', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E2', default_event_type: 'PREMIUM_FINANCIAL_REPORTING', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  openai_news: { source_id: 'openai_news', source_name: 'OpenAI News', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  anthropic_news: { source_id: 'anthropic_news', source_name: 'Anthropic News', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  deepseek_updates: { source_id: 'deepseek_updates', source_name: 'DeepSeek Updates', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  xai_releases: { source_id: 'xai_releases', source_name: 'xAI Releases', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  ndrc_policy: { source_id: 'ndrc_policy', source_name: 'NDRC Policy Announcements', domain: 'geopolitics', source_type: 'official', primary_layer: 'friction', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  ccgp_central_tenders: { source_id: 'ccgp_central_tenders', source_name: 'CCGP Central Tenders', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'CLINICAL_TRIAL_UPDATE', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  ccgp_central_awards: { source_id: 'ccgp_central_awards', source_name: 'CCGP Central Awards', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'TRADE_FLOW_RECORDED', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  state_grid_procurement: { source_id: 'state_grid_procurement', source_name: 'State Grid Procurement', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'CLINICAL_TRIAL_UPDATE', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  nha_disease_outbreaks: { source_id: 'nha_disease_outbreaks', source_name: 'NHA Disease Outbreaks', domain: 'health', source_type: 'official', primary_layer: 'friction', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'negative', default_confidence: 'high' },
  samr_consumer_safety: { source_id: 'samr_consumer_safety', source_name: 'SAMR Consumer Safety', domain: 'geopolitics', source_type: 'official', primary_layer: 'friction', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'negative', default_confidence: 'high' },
  mofcom_supply_price: { source_id: 'mofcom_supply_price', source_name: 'MOFCOM Supply Prices', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  weibo_hotsearch: { source_id: 'weibo_hotsearch', source_name: 'Weibo Hot Search', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  baidu_hotsearch: { source_id: 'baidu_hotsearch', source_name: 'Baidu Hot Search', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  douyin_public_hotlist: { source_id: 'douyin_public_hotlist', source_name: 'Douyin Public Hotlist', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  toutiao_hotboard: { source_id: 'toutiao_hotboard', source_name: 'Toutiao Hotboard', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  bilibili_popular: { source_id: 'bilibili_popular', source_name: 'Bilibili Popular', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  v2ex_hot: { source_id: 'v2ex_hot', source_name: 'V2EX Hot', domain: 'technology', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  zhihu_official_hotlist: { source_id: 'zhihu_official_hotlist', source_name: 'Zhihu Official Hotlist', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  google_trends_us: { source_id: 'google_trends_us', source_name: 'Google Trends US', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E2', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  google_trends_hk: { source_id: 'google_trends_hk', source_name: 'Google Trends HK', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E2', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  google_trends_tw: { source_id: 'google_trends_tw', source_name: 'Google Trends TW', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E2', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  federal_register: { source_id: 'federal_register', source_name: 'Federal Register', domain: 'geopolitics', source_type: 'official', primary_layer: 'friction', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  world_bank_gdp: { source_id: 'world_bank_gdp', source_name: 'World Bank GDP', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  cboe_vix: { source_id: 'cboe_vix', source_name: 'CBOE VIX', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['friction'], default_evidence_strength: 'E3', default_event_type: 'MARKET_SENTIMENT_INDEX', default_stage_effect: 'watch_upgrade', default_polarity: 'negative', default_confidence: 'high' },
  coinbase_market: { source_id: 'coinbase_market', source_name: 'Coinbase Market', domain: 'financial', source_type: 'company', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E2', default_event_type: 'CRYPTO_SPOT_PRICE', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  
  // --- Second Batch (Business Baselines) ---
  '36kr': { source_id: '36kr', source_name: '36Kr', domain: 'technology', source_type: 'news', primary_layer: 'capital', secondary_layers: ['name'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  jiqizhixin: { source_id: 'jiqizhixin', source_name: 'Jiqizhixin (Synced)', domain: 'technology', source_type: 'news', primary_layer: 'name', secondary_layers: ['reality'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  qbitai: { source_id: 'qbitai', source_name: 'QbitAI', domain: 'technology', source_type: 'news', primary_layer: 'name', secondary_layers: ['reality'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  infoq_cn: { source_id: 'infoq_cn', source_name: 'InfoQ China', domain: 'technology', source_type: 'news', primary_layer: 'name', secondary_layers: ['reality'], default_evidence_strength: 'E2', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  people_daily_headlines: { source_id: 'people_daily_headlines', source_name: 'People Daily Headlines', domain: 'geopolitics', source_type: 'news', primary_layer: 'friction', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'GLOBAL_WIRE_NEWS', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  cninfo_announcements: { source_id: 'cninfo_announcements', source_name: 'Cninfo Announcements', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  sse_announcements: { source_id: 'sse_announcements', source_name: 'SSE Announcements', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  szse_announcements: { source_id: 'szse_announcements', source_name: 'SZSE Announcements', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  '1688_search_trends': { source_id: '1688_search_trends', source_name: '1688 Search Trends', domain: 'financial', source_type: 'other', primary_layer: 'capital', secondary_layers: ['name'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  csg_enterprise_procurement: { source_id: 'csg_enterprise_procurement', source_name: 'CSG Enterprise Procurement', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'TRADE_FLOW_RECORDED', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  
  // --- Third Batch (API Keys required) ---
  alpha_vantage_spy: { source_id: 'alpha_vantage_spy', source_name: 'Alpha Vantage SPY', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'MARKET_SENTIMENT_INDEX', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  alpha_vantage_qqq: { source_id: 'alpha_vantage_qqq', source_name: 'Alpha Vantage QQQ', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'MARKET_SENTIMENT_INDEX', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  douyin_official_hotsearch: { source_id: 'douyin_official_hotsearch', source_name: 'Douyin Official Hotsearch', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'MARKET_TRENDING_ASSET', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  x_official_recent_search: { source_id: 'x_official_recent_search', source_name: 'X Official Recent Search', domain: 'osint', source_type: 'other', primary_layer: 'name', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
  deepsearch_external_discovery: { source_id: 'deepsearch_external_discovery', source_name: 'DeepSearch External Discovery', domain: 'research', source_type: 'other', primary_layer: 'name', secondary_layers: ['reality'], default_evidence_strength: 'E1', default_event_type: 'GLOBAL_NEWS_EVENT', default_stage_effect: 'maintain', default_polarity: 'neutral', default_confidence: 'low' },

  // --- Fourth Batch (Phase 4 Expansions) ---
  fed_statements: { source_id: 'fed_statements', source_name: 'Federal Reserve Statements', domain: 'financial', source_type: 'official', primary_layer: 'friction', secondary_layers: ['pricing'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  pboc_announcements: { source_id: 'pboc_announcements', source_name: 'PBOC Announcements', domain: 'financial', source_type: 'official', primary_layer: 'friction', secondary_layers: ['pricing'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  cnipa_patents: { source_id: 'cnipa_patents', source_name: 'CNIPA Patents', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E2', default_event_type: 'TRADE_FLOW_RECORDED', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  uspto_patents: { source_id: 'uspto_patents', source_name: 'USPTO Patents', domain: 'technology', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E2', default_event_type: 'TRADE_FLOW_RECORDED', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },
  cpca_auto_sales: { source_id: 'cpca_auto_sales', source_name: 'CPCA Auto Sales', domain: 'financial', source_type: 'official', primary_layer: 'capital', secondary_layers: ['reality'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  bdi_index: { source_id: 'bdi_index', source_name: 'Baltic Dry Index', domain: 'financial', source_type: 'official', primary_layer: 'pricing', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'INSTITUTIONAL_MACRO_DATA', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  tech_giants_careers: { source_id: 'tech_giants_careers', source_name: 'Tech Giants Careers', domain: 'osint', source_type: 'company', primary_layer: 'reality', secondary_layers: ['momentum'], default_evidence_strength: 'E1', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'medium' },

  // --- Institutional 5D Intelligence Grid Additions ---
  gov_cn: { source_id: 'gov_cn', source_name: '中国政府网 (国务院政策库与国务院令)', domain: 'official', source_type: 'official', primary_layer: 'name', secondary_layers: ['reality', 'friction'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_POLICY', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  eastmoney_reports: { source_id: 'eastmoney_reports', source_name: '东方财富研报中心 (13.9万券商深度研报库)', domain: 'financial', source_type: 'company', primary_layer: 'pricing', secondary_layers: ['capital', 'reality'], default_evidence_strength: 'E2', default_event_type: 'RESEARCH_REPORT', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  cninfo_disclosures: { source_id: 'cninfo_disclosures', source_name: '巨潮资讯网 (A股上市公司重大法定公告)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  vip_leaders_stream: { source_id: 'vip_leaders_stream', source_name: '全球关键领袖专线 (黄仁勋/马斯克/曾毓群/任正非/雷军)', domain: 'technology', source_type: 'company', primary_layer: 'name', secondary_layers: ['reality', 'capital'], default_evidence_strength: 'E2', default_event_type: 'MARKET_FACT', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  nmpa_cde: { source_id: 'nmpa_cde', source_name: '国家药监局药品审评中心 (CDE 临床与上市审评批件)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['friction'], default_evidence_strength: 'E3', default_event_type: 'CLINICAL_TRIAL_UPDATE', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  caac_evtol: { source_id: 'caac_evtol', source_name: '中国民用航空局 (CAAC 低空经济适航三证许可)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['friction'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_POLICY', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  csrc_announcements: { source_id: 'csrc_announcements', source_name: '中国证监会 / 沪深北交易所 (IPO重组与再融资批文)', domain: 'official', source_type: 'official', primary_layer: 'capital', secondary_layers: ['friction'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  hkex_news: { source_id: 'hkex_news', source_name: '香港交易所披露易 (HKEX 18A 生物科技与特专科技公告)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_SEC_FILING', default_stage_effect: 'upgrade', default_polarity: 'neutral', default_confidence: 'high' },
  nea_energy: { source_id: 'nea_energy', source_name: '国家能源局 (新型储能与示范项目工程批文)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['capital'], default_evidence_strength: 'E3', default_event_type: 'OFFICIAL_POLICY', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  wipo_patents: { source_id: 'wipo_patents', source_name: '世界知识产权组织 (WIPO PCT 国际前沿专利公布)', domain: 'official', source_type: 'official', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'TRADE_FLOW_RECORDED', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  nature_electronics: { source_id: 'nature_electronics', source_name: 'Nature Electronics & Nature Biotech (前沿学术突破)', domain: 'research', source_type: 'news', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'PREMIUM_FINANCIAL_REPORTING', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  science_robotics: { source_id: 'science_robotics', source_name: 'Science Robotics & Materials (顶级基础科研与机器人)', domain: 'research', source_type: 'news', primary_layer: 'reality', secondary_layers: ['name'], default_evidence_strength: 'E3', default_event_type: 'PREMIUM_FINANCIAL_REPORTING', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  pubmed_nih: { source_id: 'pubmed_nih', source_name: 'PubMed / NCBI (美国国立卫生研究院全球医学文献)', domain: 'research', source_type: 'news', primary_layer: 'reality', secondary_layers: ['data_confidence'], default_evidence_strength: 'E3', default_event_type: 'PREMIUM_FINANCIAL_REPORTING', default_stage_effect: 'upgrade', default_polarity: 'positive', default_confidence: 'high' },
  semianalysis_intel: { source_id: 'semianalysis_intel', source_name: 'SemiAnalysis (全球半导体先进封装与晶圆成本模型)', domain: 'technology', source_type: 'news', primary_layer: 'reality', secondary_layers: ['pricing'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  the_information: { source_id: 'the_information', source_name: 'The Information (硅谷前沿独角兽与算力集群深度调研)', domain: 'technology', source_type: 'news', primary_layer: 'reality', secondary_layers: ['capital'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  pitchbook_deals: { source_id: 'pitchbook_deals', source_name: 'PitchBook (全球 PE/VC 硬科技独角兽融资数据库)', domain: 'financial', source_type: 'company', primary_layer: 'capital', secondary_layers: ['pricing'], default_evidence_strength: 'E2', default_event_type: 'TECH_STARTUP_FUNDING', default_stage_effect: 'watch_upgrade', default_polarity: 'positive', default_confidence: 'high' },
  xueqiu_institutional: { source_id: 'xueqiu_institutional', source_name: '雪球机构调研纪要与买方交流库', domain: 'financial', source_type: 'company', primary_layer: 'capital', secondary_layers: ['pricing'], default_evidence_strength: 'E1', default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL', default_stage_effect: 'watch_upgrade', default_polarity: 'neutral', default_confidence: 'medium' },
};

/**
 * Maps live operation ids to canonical catalog keys so the sync path resolves
 * the same per-source lifecycle configuration as the legacy connector.
 */
const OPERATION_TO_SOURCE_ID: Record<string, string> = {
  DirectGdeltDocArticles: 'gdelt_doc_articles',
  DirectCoinbaseSpotPrice: 'coinbase_spot',
  DirectEastmoneyConceptBoards: 'eastmoney_concept_boards',
  DirectEastmoneyStockQuote: 'eastmoney_stock_quote',
  DirectClinicalTrialsGovStudies: 'clinical_trials_gov',
  DirectUnComtradePreview: 'un_comtrade_preview',
  DirectSecEdgarNvidia: 'sec_edgar_nvidia',
  DirectSecEdgarApple: 'sec_edgar_apple',
  DirectSecEdgarTsmc: 'sec_edgar_tsmc',
  DirectHackerNewsStories: 'hacker_news_stories',
  DirectFearGreedIndex: 'fear_greed_index',
  DirectCoinGeckoTrending: 'coingecko_trending',
  DirectCailianTelegraph: 'cailian_telegraph',
  DirectWSJBusiness: 'wsj_business',
  DirectWSJChinese: 'wsj_business',
  DirectReutersBiz: 'reuters_biz',
  DirectTechCrunch: 'tech_crunch',
  DirectNtsFinance: 'nts_finance',
  DirectNtsTechnology: 'nts_technology',
  DirectNtsEtf: 'nts_etf',
  DirectNtsResearch: 'nts_research',
  DirectInvestingMacro: 'investing_macro',
  DirectInvestingStock: 'investing_stock',
  DirectInvestingAnalysis: 'investing_analysis',
  DirectInvestingCrypto: 'investing_crypto',
  DirectHuggingFace: 'huggingface',
  DirectGithubIssues: 'github_issues',
  DirectGithubTrending: 'github_trending',
  DirectArxivAi: 'arxiv_ai',
  DirectOpenAiNews: 'openai_news',
  DirectAnthropicNews: 'anthropic_news',
  DirectDeepseekUpdates: 'deepseek_updates',
  DirectXaiReleases: 'xai_releases',
  DirectNdrcPolicy: 'ndrc_policy',
  DirectCcgpCentralTenders: 'ccgp_central_tenders',
  DirectCcgpCentralAwards: 'ccgp_central_awards',
  DirectStateGridProcurement: 'state_grid_procurement',
  DirectNhaDiseaseOutbreaks: 'nha_disease_outbreaks',
  DirectSamrConsumerSafety: 'samr_consumer_safety',
  DirectMofcomSupplyPrice: 'mofcom_supply_price',
  DirectWeiboHotsearch: 'weibo_hotsearch',
  DirectBaiduHotsearch: 'baidu_hotsearch',
  DirectDouyinPublicHotlist: 'douyin_public_hotlist',
  DirectToutiaoHotboard: 'toutiao_hotboard',
  DirectBilibiliPopular: 'bilibili_popular',
  DirectV2exHot: 'v2ex_hot',
  DirectZhihuOfficialHotlist: 'zhihu_official_hotlist',
  DirectGoogleTrendsUs: 'google_trends_us',
  DirectGoogleTrendsHk: 'google_trends_hk',
  DirectGoogleTrendsTw: 'google_trends_tw',
  DirectFederalRegister: 'federal_register',
  DirectWorldBankGdp: 'world_bank_gdp',
  DirectCboeVix: 'cboe_vix',
  DirectCoinbaseMarket: 'coinbase_market',
  
  Direct36kr: '36kr',
  DirectJiqizhixin: 'jiqizhixin',
  DirectQbitai: 'qbitai',
  DirectInfoqCn: 'infoq_cn',
  DirectPeopleDailyHeadlines: 'people_daily_headlines',
  DirectCninfoAnnouncements: 'cninfo_announcements',
  DirectSseAnnouncements: 'sse_announcements',
  DirectSzseAnnouncements: 'szse_announcements',
  Direct1688SearchTrends: '1688_search_trends',
  DirectCsgEnterpriseProcurement: 'csg_enterprise_procurement',
  
  DirectAlphaVantageSpy: 'alpha_vantage_spy',
  DirectAlphaVantageQqq: 'alpha_vantage_qqq',
  DirectDouyinOfficialHotsearch: 'douyin_official_hotsearch',
  DirectXOfficialRecentSearch: 'x_official_recent_search',
  DirectDeepsearchExternalDiscovery: 'deepsearch_external_discovery',

  DirectFedStatements: 'fed_statements',
  DirectPbocAnnouncements: 'pboc_announcements',
  DirectCnipaPatents: 'cnipa_patents',
  DirectUsptoPatents: 'uspto_patents',
  DirectCpcaAutoSales: 'cpca_auto_sales',
  DirectBdiIndex: 'bdi_index',
  DirectTechGiantsCareers: 'tech_giants_careers',

};

export function sourceConfigForSourceId(sourceId: string): WorldMonitorSourceConfig | null {
  return WORLDMONITOR_SOURCE_CATALOG[sourceId] ?? FEED_SOURCE_CATALOG[sourceId] ?? null;
}

export function operationSourceConfig(operationId: string): WorldMonitorSourceConfig | null {
  const sourceId = OPERATION_TO_SOURCE_ID[operationId] ?? FEED_OPERATION_TO_SOURCE_ID[operationId];
  return sourceId ? sourceConfigForSourceId(sourceId) : null;
}
