/** Curated market-facing Chinese names. IDs remain stable for audit/history. */
export const TOPIC_NAME_LOCALIZATIONS: Readonly<Record<string, string>> = {
  // Core & Canonical
  bci: '脑机接口',
  '脑机接口 BCI': '脑机接口',
  provisional_bci: '脑机接口',
  humanoid_robotics: '人形机器人',
  '人形机器人 / 具身智能': '人形机器人',
  provisional_humanoid_robotics: '人形机器人',
  innovative_drug_license_out: '创新药对外授权',
  '创新药 License-out': '创新药对外授权',
  solid_state_battery: '固态电池',
  provisional_solid_state_battery: '固态电池',
  sodium_ion_battery: '钠离子电池',
  provisional_sodium_ion_battery: '钠离子电池',

  // Provisional & Industry topics
  provisional_additive_manufacturing: '增材制造',
  provisional_advanced_packaging: '先进封装',
  provisional_ai_agents: 'AI智能体',
  provisional_ai_foundation_models: '基础大模型',
  provisional_ai_software: 'AI软件',
  provisional_ai_video_generation: 'AI视频生成',
  provisional_antibody_drug_conjugates: '抗体偶联药物',
  provisional_autonomous_driving: '自动驾驶',
  provisional_autonomous_driving_robotaxi: '自动驾驶与无人出租车',
  provisional_banking_credit_ratings: '银行信用评级',
  provisional_biopharma_annual_reporting: '生物医药年报',
  provisional_blockchain_crypto_market: '区块链与加密资产',
  provisional_china_a_share_disclosure_enforcement: 'A股信息披露监管',
  provisional_china_ip_policy: '中国知识产权政策',
  provisional_china_macro_policy: '中国宏观政策',
  provisional_china_premarket_briefing: '中国市场盘前动态',
  provisional_china_prominent_deaths: '中国重要人物逝世',
  provisional_china_social_security_policy: '社会保障政策',
  provisional_climate_adaptation: '气候适应',
  provisional_commercial_space: '商业航天',
  provisional_computing_infrastructure: '算力基础设施',
  provisional_cross_border_ecommerce: '跨境电商',
  provisional_cybersecurity: '网络安全',
  provisional_defense_informationization: '国防信息化',
  provisional_fusion_energy_supply_chain: '核聚变产业链',
  provisional_gold_2027_outlook: '黄金2027年展望',
  provisional_gold_macro_macro_data: '黄金宏观数据',
  provisional_hk_equities_market_action: '港股市场动态',
  provisional_india_commodity_derivatives_expansion: '印度商品衍生品扩张',
  provisional_india_equities_earnings_action: '印度股市财报动态',
  provisional_india_invit_regulation: '印度基础设施投资信托监管',
  provisional_industrial_software: '工业软件',
  provisional_infectious_disease_outbreaks: '传染病暴发',
  provisional_innovative_drug_approval: '创新药审批',
  provisional_innovative_drug_clinical_development: '创新药临床研发',
  provisional_korea_leveraged_etf_regulation: '韩国杠杆ETF监管',
  provisional_latch_shareholder_derivative_settlement: 'Latch股东衍生诉讼和解',
  provisional_logistics_supply_chain: '物流与供应链',
  provisional_low_altitude_economy: '低空经济',
  provisional_luxury_consumer: '高端消费',
  provisional_medicine: '医药',
  provisional_new_energy_industry: '新能源产业',
  provisional_new_energy_storage: '新型储能',
  provisional_nuclear_fusion_advanced_nuclear: '可控核聚变与先进核能',
  provisional_payment_security_assessor_market: '支付安全评估市场',
  provisional_quantum_computing: '量子计算',
  provisional_radiopharmaceuticals: '放射性药物',
  provisional_real_estate_new_model: '房地产发展新模式',
  provisional_semiconductor_advanced_manufacturing: '半导体先进制造',
  provisional_semiconductor_ip_policy: '半导体知识产权政策',
  provisional_semiconductor_memory_market: '存储芯片',
  provisional_smart_manufacturing: '智能制造',
  provisional_spatial_computing_xr: '空间计算与扩展现实',
  provisional_synthetic_biology: '合成生物学',
  provisional_traditional_chinese_medicine_revival: '中医药振兴',
  provisional_us_asset_management_consolidation: '美国资产管理行业整合',
  provisional_us_equities_daily_session: '美股每日行情',
  provisional_us_index_rebalance_effects: '美国指数再平衡影响',
  provisional_us_jen_intervention: '日元干预',
  provisional_wind_power: '风电',
};
