import type { WorldMonitorSourceConfig } from '../types/worldmonitor_adapter';
import {
  FEED_OPERATION_TO_SOURCE_ID,
  FEED_SOURCE_CATALOG,
} from './worldmonitor_feed_catalog';

/**
 * Canonical per-source lifecycle mapping catalog.
 *
 * This table is the single source of truth that maps World Monitor sources
 * (both worldmonitor_hosted and direct_public) to lifecycle layers, default
 * evidence strength, event types and review defaults. It was migrated from
 * the legacy WorldMonitorIntakeConnector so that the live sync path and the
 * legacy signal connector share one configuration. See docs/27 for the
 * integration map this table implements.
 */
export const WORLDMONITOR_SOURCE_CATALOG: Record<string, WorldMonitorSourceConfig> = {
  // Category 1: Geopolitics, Conflict & Military
  acled: {
    source_id: 'acled',
    source_name: 'ACLED Armed Conflict Location Event Data',
    domain: 'geopolitics',
    source_type: 'official',
    primary_layer: 'friction',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E2',
    default_event_type: 'CONFLICT_EVENT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  ucdp: {
    source_id: 'ucdp',
    source_name: 'Uppsala Conflict Data Program',
    domain: 'geopolitics',
    source_type: 'official',
    primary_layer: 'friction',
    secondary_layers: ['data_confidence'],
    default_evidence_strength: 'E2',
    default_event_type: 'STATE_CONFLICT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  gdelt: {
    source_id: 'gdelt',
    source_name: 'GDELT Global Event Database',
    domain: 'geopolitics',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E1',
    default_event_type: 'GLOBAL_NEWS_EVENT',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  military_bases: {
    source_id: 'military_bases',
    source_name: 'Global Military Base Posture Watch',
    domain: 'geopolitics',
    source_type: 'research',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E2',
    default_event_type: 'BASE_POSTURE_CHANGE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  military_flights: {
    source_id: 'military_flights',
    source_name: 'OpenSky / ADS-B Military Aviation Tracker',
    domain: 'geopolitics',
    source_type: 'other',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E2',
    default_event_type: 'AIR_RECON_SURGE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  military_maritime: {
    source_id: 'military_maritime',
    source_name: 'Naval Operations & Fleet Deployment Feed',
    domain: 'geopolitics',
    source_type: 'news',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E2',
    default_event_type: 'NAVAL_DEPLOYMENT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'medium',
  },
  oref_sirens: {
    source_id: 'oref_sirens',
    source_name: 'OREF IDF Siren Alert Feed',
    domain: 'geopolitics',
    source_type: 'official',
    primary_layer: 'friction',
    secondary_layers: [],
    default_evidence_strength: 'E3',
    default_event_type: 'ROCKET_SIREN_ALERT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  defense_tenders: {
    source_id: 'defense_tenders',
    source_name: 'SAM.gov & TED Defense Procurement Tenders',
    domain: 'geopolitics',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'GOVT_CONTRACT_AWARD',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  sanctions: {
    source_id: 'sanctions',
    source_name: 'OFAC & FATF Sanctions Tracker',
    domain: 'geopolitics',
    source_type: 'official',
    primary_layer: 'friction',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E3',
    default_event_type: 'SANCTION_IMPOSED',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },

  // Category 2: Financial Markets, Macro & Sentiment
  market_quotes: {
    source_id: 'market_quotes',
    source_name: 'Finnhub Global Equity Quotes',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'STOCK_INDEX_BREAKOUT',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  gulf_quotes: {
    source_id: 'gulf_quotes',
    source_name: 'GCC Gulf Markets Feed',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: [],
    default_evidence_strength: 'E2',
    default_event_type: 'GULF_MARKET_SHIFT',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  commodity_quotes: {
    source_id: 'commodity_quotes',
    source_name: 'Energy & Commodity Futures Pricing',
    domain: 'financial',
    source_type: 'other',
    primary_layer: 'pricing',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E3',
    default_event_type: 'COMMODITY_PRICE_SPIKE',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  fred_economy: {
    source_id: 'fred_economy',
    source_name: 'US Federal Reserve FRED Macro Data',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'pricing',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'MACRO_RATE_REVISION',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  imf_macro: {
    source_id: 'imf_macro',
    source_name: 'IMF World Economic Outlook & SDMX Data',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'pricing',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E2',
    default_event_type: 'IMF_GDP_FORECAST_REVISION',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  wb_indicators: {
    source_id: 'wb_indicators',
    source_name: 'World Bank WDI Development Indicators',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'pricing',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E2',
    default_event_type: 'WB_INDICATOR_UPDATE',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  china_macro: {
    source_id: 'china_macro',
    source_name: 'PBOC & China Macroeconomic Disclosures',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'capital',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E3',
    default_event_type: 'CHINA_TSF_POLICY_SHIFT',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  cftc_cot: {
    source_id: 'cftc_cot',
    source_name: 'CFTC Commitment of Traders (COT) Reports',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'COT_POSITIONING_SHIFT',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  prediction_markets: {
    source_id: 'prediction_markets',
    source_name: 'Polymarket & Prediction Market Odds',
    domain: 'financial',
    source_type: 'other',
    primary_layer: 'pricing',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'PREDICTION_ODDS_SHIFT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },

  // Category 3: Energy, Supply Chain & Maritime Tracking
  portwatch: {
    source_id: 'portwatch',
    source_name: 'IMF PortWatch Chokepoint & Transit Tracker',
    domain: 'energy',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'PORT_DISRUPTION_ALERT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  eia_petroleum: {
    source_id: 'eia_petroleum',
    source_name: 'US EIA Weekly Petroleum Statistics',
    domain: 'energy',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E3',
    default_event_type: 'EIA_INVENTORY_DRAWDOWN',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  gie_gas: {
    source_id: 'gie_gas',
    source_name: 'AGSI+ European Natural Gas Storage',
    domain: 'energy',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'EU_GAS_STORAGE_LEVEL',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  comtrade_trade: {
    source_id: 'comtrade_trade',
    source_name: 'UN Comtrade Bilateral Customs Data',
    domain: 'energy',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'CRITICAL_MINERAL_EXPORTS',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },

  // Category 4: Aviation, Infrastructure & Remote Sensing
  aviation_stack: {
    source_id: 'aviation_stack',
    source_name: 'AviationStack & Airspace NOTAM Monitor',
    domain: 'infrastructure',
    source_type: 'other',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E2',
    default_event_type: 'FLIGHT_DELAY_SPIKE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'medium',
  },
  gpsjam: {
    source_id: 'gpsjam',
    source_name: 'GPSJAM Electronic Warfare Tracker',
    domain: 'infrastructure',
    source_type: 'other',
    primary_layer: 'friction',
    secondary_layers: [],
    default_evidence_strength: 'E2',
    default_event_type: 'GPS_JAMMING_HOTSPOT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  firms_fires: {
    source_id: 'firms_fires',
    source_name: 'NASA FIRMS Satellite Thermal Points',
    domain: 'infrastructure',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E3',
    default_event_type: 'THERMAL_ANOMALY_DETECTED',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },
  submarine_cables: {
    source_id: 'submarine_cables',
    source_name: 'Cloudflare Radar Submarine Cable Outages',
    domain: 'infrastructure',
    source_type: 'company',
    primary_layer: 'friction',
    secondary_layers: ['reality'],
    default_evidence_strength: 'E3',
    default_event_type: 'INTERNET_OUTAGE_ALERT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'negative',
    default_confidence: 'high',
  },

  // Category 5: News, OSINT & Intelligence Synthesis
  rss_feeds: {
    source_id: 'rss_feeds',
    source_name: 'Global Financial & Geopolitical RSS News',
    domain: 'osint',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: [],
    default_evidence_strength: 'E1',
    default_event_type: 'NEWS_ARTICLE_PUBLISHED',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  telegram_osint: {
    source_id: 'telegram_osint',
    source_name: 'Telegram OSINT Defense & Geopolitics Feed',
    domain: 'osint',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: ['friction'],
    default_evidence_strength: 'E1',
    default_event_type: 'TELEGRAM_BREAKING_ALERT',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'mixed',
    default_confidence: 'low',
  },
  reddit_velocity: {
    source_id: 'reddit_velocity',
    source_name: 'Reddit Subreddit Velocity Tracker',
    domain: 'osint',
    source_type: 'other',
    primary_layer: 'name',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E1',
    default_event_type: 'SOCIAL_VELOCITY_BURST',
    default_stage_effect: 'maintain',
    default_polarity: 'positive',
    default_confidence: 'low',
  },
  llm_correlation: {
    source_id: 'llm_correlation',
    source_name: 'World Monitor AI Correlation Engine',
    domain: 'osint',
    source_type: 'research',
    primary_layer: 'momentum',
    secondary_layers: ['data_confidence'],
    default_evidence_strength: 'E2',
    default_event_type: 'CORRELATION_CLUSTER_IDENTIFIED',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },

  // Category 6: Direct public sources (v0.7.9+)
  gdelt_doc_articles: {
    source_id: 'gdelt_doc_articles',
    source_name: 'GDELT DOC 2.0 Global News Articles',
    domain: 'osint',
    source_type: 'news',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'GLOBAL_NEWS_EVENT',
    default_stage_effect: 'maintain',
    default_polarity: 'mixed',
    default_confidence: 'medium',
  },
  coinbase_spot: {
    source_id: 'coinbase_spot',
    source_name: 'Coinbase Public Spot Price Quotes',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'CRYPTO_SPOT_PRICE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  eastmoney_concept_boards: {
    source_id: 'eastmoney_concept_boards',
    source_name: 'A-Share Concept Board Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['name'],
    default_evidence_strength: 'E2',
    default_event_type: 'CONCEPT_BOARD_MOVE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'positive',
    default_confidence: 'medium',
  },
  eastmoney_stock_quote: {
    source_id: 'eastmoney_stock_quote',
    source_name: 'A-Share Stock Quote Monitor (Eastmoney)',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'capital',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E2',
    default_event_type: 'A_SHARE_QUOTE',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  clinical_trials_gov: {
    source_id: 'clinical_trials_gov',
    source_name: 'US NIH ClinicalTrials.gov Studies',
    domain: 'health',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['data_confidence'],
    default_evidence_strength: 'E3',
    default_event_type: 'CLINICAL_TRIAL_UPDATE',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },
  un_comtrade_preview: {
    source_id: 'un_comtrade_preview',
    source_name: 'UN Comtrade Public Preview API',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'TRADE_FLOW_RECORDED',
    default_stage_effect: 'upgrade',
    default_polarity: 'positive',
    default_confidence: 'high',
  },

  // Category 7: Leading vendor official disclosures & industry signals (v0.8.0+)
  sec_edgar_nvidia: {
    source_id: 'sec_edgar_nvidia',
    source_name: 'NVIDIA Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_apple: {
    source_id: 'sec_edgar_apple',
    source_name: 'Apple Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  sec_edgar_tsmc: {
    source_id: 'sec_edgar_tsmc',
    source_name: 'TSMC Official SEC EDGAR Submissions',
    domain: 'financial',
    source_type: 'official',
    primary_layer: 'reality',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E3',
    default_event_type: 'OFFICIAL_SEC_FILING',
    default_stage_effect: 'upgrade',
    default_polarity: 'neutral',
    default_confidence: 'high',
  },
  hacker_news_stories: {
    source_id: 'hacker_news_stories',
    source_name: 'Hacker News Developer Community Signal',
    domain: 'research',
    source_type: 'other',
    primary_layer: 'name',
    secondary_layers: ['momentum'],
    default_evidence_strength: 'E1',
    default_event_type: 'COMMUNITY_DISCUSSION_SIGNAL',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
  fear_greed_index: {
    source_id: 'fear_greed_index',
    source_name: 'Crypto Fear & Greed Market Sentiment Index',
    domain: 'financial',
    source_type: 'other',
    primary_layer: 'capital',
    secondary_layers: ['pricing'],
    default_evidence_strength: 'E2',
    default_event_type: 'MARKET_SENTIMENT_INDEX',
    default_stage_effect: 'watch_upgrade',
    default_polarity: 'neutral',
    default_confidence: 'medium',
  },
  coingecko_trending: {
    source_id: 'coingecko_trending',
    source_name: 'CoinGecko Trending Market Search Signal',
    domain: 'financial',
    source_type: 'company',
    primary_layer: 'name',
    secondary_layers: ['capital'],
    default_evidence_strength: 'E1',
    default_event_type: 'MARKET_TRENDING_ASSET',
    default_stage_effect: 'maintain',
    default_polarity: 'neutral',
    default_confidence: 'low',
  },
};

/**
 * Maps live operation ids to canonical catalog keys so the sync path resolves
 * the same per-source lifecycle configuration as the legacy connector.
 */
const OPERATION_TO_SOURCE_ID: Record<string, string> = {
  DirectGdeltDocArticles: 'gdelt_doc_articles',
  DirectCoinbaseSpotPrice: 'coinbase_spot',
  DirectEastmoneyConceptBoards: 'eastmoney_concept_boards',
  DirectEastmoneyStockQuote: 'eastmoney_stock_quote',
  DirectClinicalTrialsGovStudies: 'clinical_trials_gov',
  DirectUnComtradePreview: 'un_comtrade_preview',
  DirectSecEdgarNvidia: 'sec_edgar_nvidia',
  DirectSecEdgarApple: 'sec_edgar_apple',
  DirectSecEdgarTsmc: 'sec_edgar_tsmc',
  DirectHackerNewsStories: 'hacker_news_stories',
  DirectFearGreedIndex: 'fear_greed_index',
  DirectCoinGeckoTrending: 'coingecko_trending',
};

export function sourceConfigForSourceId(sourceId: string): WorldMonitorSourceConfig | null {
  return WORLDMONITOR_SOURCE_CATALOG[sourceId] ?? FEED_SOURCE_CATALOG[sourceId] ?? null;
}

export function operationSourceConfig(operationId: string): WorldMonitorSourceConfig | null {
  const sourceId = OPERATION_TO_SOURCE_ID[operationId] ?? FEED_OPERATION_TO_SOURCE_ID[operationId];
  return sourceId ? sourceConfigForSourceId(sourceId) : null;
}
